server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://eclient
          predicates:
            - Path=/test
            - Method=GET
        - id: name
          uri: lb://eclient-2
          predicates:
            - Path=/new/name
            - Method=GET


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka


