server:
  port: 0

spring:
  application:
    name: eclient

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

